### ISSUE TITLE
Rewrite `pr47::util::serializer` somehow

### ISSUE THREAD

**Issue by chuigda** [chuigda-wasteland/Project-47#14]
The current implementation of `pr47::util::serializer` is too ugly. What's more, I believe some abstractions may be incorrect. Clearly one `Serializer` should be shared across its task group, while something else's going to be cloned for every single task.

**Comment by chuigda** [comment]
**[SUP]** Work started on branch `serializer-next`

**Comment by CousinZe** [comment]
You assure? I think it is already clear enuf.
cc @SchrodingerZhu.

**Comment by chuigda** [comment]
Closed as won't fix

**Comment by chuigda** [comment]
Reopened in order to resolve #22

**Comment by chuigda** [comment]
Closed as resolved.
