### ISSUE TITLE
Local CI setup

### ISSUE THREAD

**Issue by chuigda** [chuigda-wasteland/Project-47#17]
We've set up GitHub Actions as our first stage CI, and this may be a good start. However, there are still certain limitations like:
- Limited to 2,000 minutes actions per month
- Not supporting windows

And GitHub Actions (and other CI products) has many reasonable but time-wasting behaviors
- Re-setup environment each time
- Re-download and re-compile all dependencies each time
- ...

While Pr47
- needs to be tested on both Windows and Linux
  - needs to be tested with both MinGW and MSVC toolchains on windows
- needs to be tested for both i686 and amd64
- needs to be tested with `miri`

A local, customized CI will be indeed necessary. By this time @CousinZe has a tiny PC, using that device will be fine I guess.

**Comment by CousinZe** [comment]
Copy that. What a pain in my ass...

**Comment by CousinZe** [comment]
Created repository at [Pr47/Marionette](https://github.com/Pr47/Marionette)

**Comment by chuigda** [comment]
Is this still ongoing, over?

**Comment by chuigda** [comment]
Closed as cancelled
