### ISSUE TITLE
Plain bytecode representation

### ISSUE THREAD

**Issue by chuigda** [chuigda-wasteland/Project-47#18]
By this time, our [byte code representation](https://github.com/Pr47/Pr47/blob/3a31aae2acbc0f02d81a9d3d880316393ece6067/pr47-core/src/vm/al31f/insc.rs#L12) includes lots of _pointers_ like:
```rust
    Call(usize, Box<[usize]>, Box<[usize]>),
    CallTyck(usize, Box<[usize]>, Box<[usize]>),
    CallPtr(usize, Box<[usize]>, Box<[usize]>),
    CallPtrTyck(usize, Box<[usize]>, Box<[usize]>),
    CallOverload(usize, Box<[usize]>, Box<[usize]>)
```

the boxed slice (`Box<[T]>`) will require an extra heap allocation on creation, and an extra indirection when interpreting bytecode. Using a plain representation might improve the overall performance of our VM.

**Comment by chuigda** [comment]
**[SUP]** A [pull request](https://github.com/Pr47/T10/pull/15) has been opened in T10 repository.

**Comment by CousinZe** [comment]
To represent byte code in plain, we must correctly align `u8`s to `64`bit. For T10 which uses unsafe Rust, we can use allocator API. For PR47 which uses stable Rust, we need a customised vector. Modifying [zvec.rs](https://github.com/Pr47/Pr47/blob/master/pr47-core/src/util/zvec.rs) will be fine.

**Comment by chuigda** [comment]
[Here](https://github.com/Pr47/T10/blob/plain-bytecode/src/turbofan/r15_300/aligned_bytes.rs) it is~

**Comment by chuigda** [comment]
This issue is closed because plain byte code representation is not somewhat better, at least according to existing benchmarks.

**Comment by chuigda** [comment]
Though, we've figured out that `u32` is generally faster than `usize` on x86_64 platform. We can optimise our interpreter according to this. Will open another pull request for this.

**Comment by chuigda** [comment]
After some testing on the `vm-u32` branch, we found that benchmarks on T10 don't always apply to Pr47. Maybe we need to do some benchmarking directly on Pr47 crate?
